### ISSUE TITLE
Model convertion

### ISSUE THREAD

**Issue by OValery16** [kkahatapitiya/X3D-Multigrid#1]
Thank you a lot for sharing your implementation. It is really helpful for implementing X3D network on custom deep learning problem. 

The original repo only provides Caffe2 pretrained model. How did you convert them to pytorch format ? (I also want to try other version of X3D)

**Comment by kkahatapitiya** [comment]
I followed a brute force approach of mapping parameter names from their version to my version. It may feel like a lot of work at first, but with print(model) and copy/paste it doesn't take that long once you see the pattern in each block.

**Comment by OValery16** [comment]
Thank you for your help.
