### ISSUE TITLE
num_samples error

### ISSUE THREAD

**Issue by giovi1** [kkahatapitiya/X3D-Multigrid#12]
Hi,

When I run train_x3d_charades.py, I get the following error:

```
raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

I'm using the same dataset in the code (Charades_v1_rgb). Do you have any suggestions? 
Thank you.

<img width="936" alt="Screenshot 2023-09-01 alle 11 35 47" src="https://github.com/kkahatapitiya/X3D-Multigrid/assets/40704475/9bba65ee-4a38-48cc-aecf-18089a539026">

**Comment by kkahatapitiya** [comment]
Sorry about the delayed response. I think this should be a problem with your dataset path. Please double-check.
