### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by iliasprc** [kkahatapitiya/X3D-Multigrid#3]
Hello, which configurations of X3d have you trained and included in the repo ? (X3D-M , X3D- L , X3D-XL ....)

**Comment by tonyduan** [comment]
Looks like both `x3d_charades_rgb_sgd_024000.pt` and `x3d_multigrid_kinetics_rgb_sgd_204000.pt` under the `models/` directory are trained with the X3D-L configuration.

**Comment by kkahatapitiya** [comment]
In fact, the pretrained models included are for X3D-M configuration

**Comment by wanghao14** [comment]
@kkahatapitiya Hi, thanks a lot for sharing your implementation! I want to use your pretrained model to do validation, and if I only have one GPU, how should I modify the super-parameters, especially **base_bn_splits** used for generating model. And I want to know wheter the model named  "x3d_multigrid_kinetics_fb_pretrained.pt" is modified from the provided by facebook? Look forward to your reply.
