### ISSUE TITLE
Changing input clip length

### ISSUE THREAD

**Issue by TheKursta** [kkahatapitiya/X3D-Multigrid#7]
Good day!

I have troubles on finding where to specify input clip length parameter when defining X3D model. Currently I'm aiming to change input frames (temporal duration parameter) to 20 for X3D-M training and so that input clip (gamma_tau) is sampled at 10FPS.
Please provide some insight on how that can be achieved.

**Comment by kkahatapitiya** [comment]
You can change [`frames=80`](https://github.com/kkahatapitiya/X3D-Multigrid/blob/3685e155268eb144fa51e1c6837d37555dc6347d/train_x3d_kinetics_multigrid.py#L110) line. If you want to consider 20 frames as the input with `gamma_tau=10`, you need to set `frames=200`. Btw, `gamma_tau=10` does not mean 10fps, it means the original frame-rate (25 or 30fps, check Kinetics paper) is subsampled by 10x
