### ISSUE TITLE
How to test video-level acc?

### ISSUE THREAD

**Issue by WUSHUANGPPP** [kkahatapitiya/X3D-Multigrid#9]
Hi,appreciate your beautiful work! @kkahatapitiya  Could you tell me how you implement  performance validation 71.48% Top-1 accuracy (3-view) on Kinetics-400？Have you opensource your video-level  accuracy test code? I test the pretrained performance lower than the performance you offered. （video-level acc which is average all clips of a test video of my approach）

**Comment by kkahatapitiya** [comment]
Sorry about the long delay in response. I compute top-1 accuracy (video-level) here: https://github.com/kkahatapitiya/X3D-Multigrid/blob/d63d8fe6210d2b38aa26d71b0062b569687d6be2/train_x3d_kinetics_multigrid.py#L263

In multi-crop testing, multiple crops are reshaped into batch dimension as in: https://github.com/kkahatapitiya/X3D-Multigrid/blob/d63d8fe6210d2b38aa26d71b0062b569687d6be2/train_x3d_kinetics_multigrid.py#L242

It can handle both single-crop and multi-crop settings with the same script.
